### ISSUE TITLE
Invoice ID on the left can not be viewed after Ruby 3.2.0 upgrade

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/ydim-html#19]
1. Single invoice can not be viewed after Ruby 3.2.0 upgrade
2. ![latest-screenshot](https://user-images.githubusercontent.com/4953/213754437-452b4d88-bcc5-4388-aa8b-c40f0d49888a.png)
3. Clicking on the "Name" nothing happens.

**Comment by ngiger** [comment]
Going to http://127.0.0.1:8050/de/ydim/debitor/unique_id/1
Clicking on name or E-Mail reloads the debitor. I think this is intentional.
Clicking on Beschreibung or Datum loads the invoice.

**Comment by zdavatz** [comment]
Clicking on the name used to work and should work.

**Comment by ngiger** [comment]
Testing with ruby 3.1.1 and htmlgrid 1.1.5 (but not with 1.1.4 or 1.1.6) the link below ID is shown.

* 1.1.6: No error but ID is not show
* 1.1.4: Produces error  can't modify frozen String: ""

**Comment by ngiger** [comment]
Setting htmlgrid to 1.1.5, adding net-imap, net-pop, net-smtp, rexml, webrick to Gemfile and upgrading bundler and sbsm I managed to start with ruby 3.2.0 and seeing the correct link below ID.
Therefore must see what broke it between htmlgrid 1.1.5 and 1.2.0

**Comment by ngiger** [comment]
Bei mir sieht es gut aus:
![image](https://user-images.githubusercontent.com/265800/213875385-44e06fed-7dbd-4e58-b6ff-ba60329831e3.png)
